CREATE TABLE [dbo].[Operation]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Status] NVARCHAR(50) NOT NULL, 
    [LeaderOIB] BIGINT NOT NULL,
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [FK_LeaderOIB] FOREIGN KEY (LeaderOIB) REFERENCES Users(OIB)
)
